name: cakeflix.com
favicon: null
layout_spectrum: 0.33019
typography_spectrum: 0.9010304354596883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6d6d6'
    - '#404040'
    - '#a3a3a3'
    - '#bdbdbd'
    - '#6e6e6e'
  brandStrength: 0
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 0.05368220875971019
purpose: []
